name: Build & Deploy

on:
  push:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: echo "css-colors.radi.pro" > build/CNAME
      - run: git add build/
      - run: git commit -m "Deploy gh-pages"
      - run: git subtree push --prefix build origin gh-pages
